package fi.riista.feature.permit.decision.document;

public enum PermitDecisionSectionIdentifier {
    APPLICATION,
    APPLICATION_REASONING,
    PROCESSING,
    DECISION,
    DECISION_EXTRA,
    DECISION_REASONING,
    RESTRICTION,
    RESTRICTION_EXTRA,
    EXECUTION,
    LEGAL_ADVICE,
    NOTIFICATION_OBLIGATION,
    APPEAL,
    ADDITIONAL_INFO,
    DELIVERY,
    PAYMENT,
    ADMINISTRATIVE_COURT,
    ATTACHMENTS
}
