package fi.riista.feature.organization.rhy.annualstats.export;

import fi.riista.util.LocalisedEnum;

public enum AnnualStatisticItemId implements LocalisedEnum {

    IBAN,
    OPERATIONAL_LAND_AREA_SIZE,

    RHY_MEMBERS,
    STATE_AID_HUNTER_TRAINING_EVENTS,
    SCHOOL_AND_COLLEGE_TRAINING_EVENTS,
    SUM_OF_LUKE_CALCULATIONS,
    SRVA_ALL_MOOSELIKE_EVENTS(true),
    SRVA_ALL_LARGE_CARNIVORE_EVENTS(true),
    SRVA_ALL_WILD_BOAR_EVENTS(true),

    HUNTER_EXAM_EVENTS,
    ALL_HUNTER_EXAM_ATTEMPTS,
    PASSED_HUNTER_EXAM_ATTEMPTS,
    FAILED_HUNTER_EXAM_ATTEMPTS,
    ASSIGNED_HUNTER_EXAM_OFFICIALS,

    ALL_SHOOTING_TEST_EVENTS,
    FIREARM_TEST_EVENTS(true),
    BOW_TEST_EVENTS(true),
    ALL_SHOOTING_TEST_ATTEMPTS,
    ALL_MOOSE_ATTEMPTS,
    QUALIFIED_MOOSE_ATTEMPTS,
    ALL_BEAR_ATTEMPTS,
    QUALIFIED_BEAR_ATTEMPTS,
    ALL_ROE_DEER_ATTEMPTS,
    QUALIFIED_ROE_DEER_ATTEMPTS,
    ALL_BOW_ATTEMPTS,
    QUALIFIED_BOW_ATTEMPTS,
    SHOOTING_TEST_OFFICIALS,

    GAME_DAMAGE_LOCATIONS_MOOSELIKE,
    GAME_DAMAGE_EXPENSES_MOOSELIKE,
    GAME_DAMAGE_LOCATIONS_LARGE_CARNIVORE,
    GAME_DAMAGE_EXPENSES_LARGE_CARNIVORE,
    GAME_DAMAGE_LOCATIONS_TOTAL,
    GAME_DAMAGE_EXPENSES_TOTAL,
    GAME_DAMAGE_INSPECTORS,

    HUNTING_CONTROL_EVENTS,
    HUNTING_CONTROL_CUSTOMERS,
    HUNTING_CONTROL_PROOF_ORDERS,
    HUNTING_CONTROLLERS,

    GRANTED_RECREATIONAL_SHOOTING_CERTIFICATES,
    MUTUAL_ACK_SHOOTING_CERTIFICATES,

    SRVA_ALL_EVENTS,
    SRVA_TOTAL_WORK_HOURS,
    SRVA_TOTAL_PARTICIPANTS,
    SRVA_ALL_ACCIDENTS,
    SRVA_TRAFFIC_ACCIDENTS(true),
    SRVA_RAILWAY_ACCIDENTS(true),
    SRVA_OTHER_ACCIDENTS(true),
    SRVA_ALL_DEPORTATIONS,
    SRVA_ALL_INJURIES,

    ALL_TRAINING_EVENTS,
    ALL_TRAINING_PARTICIPANTS,

    HUNTER_EXAM_TRAINING_EVENTS,
    HUNTER_EXAM_TRAINING_PARTICIPANTS,

    SHOOTING_TEST_TRAINING_EVENTS,
    SHOOTING_TEST_TRAINING_PARTICIPANTS,
    HUNTER_EXAM_OFFICIAL_TRAINING_EVENTS,
    HUNTER_EXAM_OFFICIAL_TRAINING_PARTICIPANTS,
    GAME_DAMAGE_TRAINING_EVENTS,
    GAME_DAMAGE_TRAINING_PARTICIPANTS,
    HUNTING_CONTROL_TRAINING_EVENTS,
    HUNTING_CONTROL_TRAINING_PARTICIPANTS,

    MOOSELIKE_HUNTING_TRAINING_EVENTS,
    MOOSELIKE_HUNTING_TRAINING_PARTICIPANTS,
    MOOSELIKE_HUNTING_LEADER_TRAINING_EVENTS,
    MOOSELIKE_HUNTING_LEADER_TRAINING_PARTICIPANTS,
    CARNIVORE_HUNTING_TRAINING_EVENTS,
    CARNIVORE_HUNTING_TRAINING_PARTICIPANTS,
    CARNIVORE_HUNTING_LEADER_TRAINING_EVENTS,
    CARNIVORE_HUNTING_LEADER_TRAINING_PARTICIPANTS,
    SRVA_TRAINING_EVENTS,
    SRVA_TRAINING_PARTICIPANTS,
    CARNIVORE_CONTACT_PERSON_TRAINING_EVENTS,
    CARNIVORE_CONTACT_PERSON_TRAINING_PARTICIPANTS,
    ACCIDENT_PREVENTION_TRAINING_EVENTS,
    ACCIDENT_PREVENTION_TRAINING_PARTICIPANTS,
    SCHOOL_TRAINING_EVENTS,
    SCHOOL_TRAINING_PARTICIPANTS,
    COLLEGE_TRAINING_EVENTS,
    COLLEGE_TRAINING_PARTICIPANTS,
    OTHER_YOUTH_TARGETED_TRAINING_EVENTS,
    OTHER_YOUTH_TARGETED_TRAINING_PARTICIPANTS,

    SMALL_CARNIVORE_HUNTING_TRAINING_EVENTS,
    SMALL_CARNIVORE_HUNTING_TRAINING_PARTICIPANTS,
    GAME_COUNTING_TRAINING_EVENTS,
    GAME_COUNTING_TRAINING_PARTICIPANTS,
    GAME_POPULATION_MANAGEMENT_TRAINING_EVENTS,
    GAME_POPULATION_MANAGEMENT_TRAINING_PARTICIPANTS,
    GAME_ENVIRONMENTAL_CARE_TRAINING_EVENTS,
    GAME_ENVIRONMENTAL_CARE_TRAINING_PARTICIPANTS,
    OTHER_GAMEKEEPING_TRAINING_EVENTS,
    OTHER_GAMEKEEPING_TRAINING_PARTICIPANTS,
    OTHER_SHOOTING_TRAINING_EVENTS,
    OTHER_SHOOTING_TRAINING_PARTICIPANTS,
    TRACKER_TRAINING_EVENTS,
    TRACKER_TRAINING_PARTICIPANTS,

    OTHER_TRAINING_EVENTS,
    OTHER_TRAINING_PARTICIPANTS,

    HARVEST_PERMIT_APPLICATION_PARTNERS,
    WOLF_TERRITORY_WORKGROUP_LEADS,

    INTERVIEWS,
    ANNOUNCEMENTS,
    OMARIISTA_ANNOUNCEMENTS,
    WWW,
    SOME_CHANNELS,
    COMMUNICATION_FREE_TEXT,

    MOOSE_RANGES,
    SHOTGUN_RANGES,
    RIFLE_RANGES,
    OTHER_SHOOTING_RANGES,

    TOTAL_GAME_TRIANGLES,
    WINTER_GAME_TRIANGLES,
    SUMMER_GAME_TRIANGLES,
    FIELD_TRIANGLES,
    WATER_BIRD_CALCULATION_LOCATIONS,

    SMALL_GAME_LICENSES_SOLD_BY_METSAHALLITUS;

    private final boolean indentedOnPrintout;

    AnnualStatisticItemId() {
        this(false);
    }

    AnnualStatisticItemId(final boolean indented) {
        this.indentedOnPrintout = indented;
    }

    public boolean isIndentedOnPrintout() {
        return indentedOnPrintout;
    }
}
