package fi.riista.feature.gamediary.harvest.fields;

import fi.riista.feature.gamediary.harvest.HarvestReportingType;

import javax.annotation.Nonnull;

import static java.util.Objects.requireNonNull;

// Fields generated by RequiredHarvestFields for given reporting type,
// game species code, hunting year and deer pilot participation.
public class RequiredHarvestReportFieldsDTO {

    @Nonnull
    public static RequiredHarvestReportFieldsDTO create(final int gameSpeciesCode,
                                                        final int huntingYear,
                                                        final @Nonnull HarvestReportingType reportingType,
                                                        final boolean isDeerPilotEnabled) {
        requireNonNull(reportingType);

        final RequiredHarvestFields.Report fieldRequirements = RequiredHarvestFields
                .getFormFields(huntingYear, gameSpeciesCode, reportingType, false, isDeerPilotEnabled);

        return create(fieldRequirements);
    }

    @Nonnull
    public static RequiredHarvestReportFieldsDTO create(final @Nonnull RequiredHarvestFields.Report report) {
        requireNonNull(report);

        final RequiredHarvestReportFieldsDTO dto = new RequiredHarvestReportFieldsDTO();

        dto.setPermitNumber(report.getPermitNumber());
        dto.setHarvestArea(report.getHarvestArea());
        dto.setHuntingMethod(report.getHuntingMethod());
        dto.setFeedingPlace(report.getFeedingPlace());
        dto.setTaigaBeanGoose(report.getTaigaBeanGoose());
        dto.setLukeStatus(report.getLukeStatus());
        dto.setHuntingAreaType(report.getHuntingAreaType());
        dto.setHuntingParty(report.getHuntingParty());
        dto.setHuntingAreaSize(report.getHuntingAreaSize());
        dto.setReportedWithPhoneCall(report.getReportedWithPhoneCall());
        dto.setDeerHuntingType(report.getDeerHuntingType());

        return dto;
    }

    private RequiredHarvestField permitNumber;
    private RequiredHarvestField harvestArea;
    private RequiredHarvestField huntingAreaType;
    private RequiredHarvestField huntingParty;
    private RequiredHarvestField huntingAreaSize;
    private RequiredHarvestField huntingMethod;
    private RequiredHarvestField reportedWithPhoneCall;
    private RequiredHarvestField feedingPlace;
    private RequiredHarvestField taigaBeanGoose;
    private RequiredHarvestField lukeStatus;
    private RequiredHarvestField deerHuntingType;

    public RequiredHarvestField getPermitNumber() {
        return permitNumber;
    }

    public void setPermitNumber(final RequiredHarvestField permitNumber) {
        this.permitNumber = permitNumber;
    }

    public RequiredHarvestField getHarvestArea() {
        return harvestArea;
    }

    public void setHarvestArea(final RequiredHarvestField harvestArea) {
        this.harvestArea = harvestArea;
    }

    public RequiredHarvestField getHuntingAreaType() {
        return huntingAreaType;
    }

    public void setHuntingAreaType(final RequiredHarvestField huntingAreaType) {
        this.huntingAreaType = huntingAreaType;
    }

    public RequiredHarvestField getHuntingParty() {
        return huntingParty;
    }

    public void setHuntingParty(final RequiredHarvestField huntingParty) {
        this.huntingParty = huntingParty;
    }

    public RequiredHarvestField getHuntingAreaSize() {
        return huntingAreaSize;
    }

    public void setHuntingAreaSize(final RequiredHarvestField huntingAreaSize) {
        this.huntingAreaSize = huntingAreaSize;
    }

    public RequiredHarvestField getHuntingMethod() {
        return huntingMethod;
    }

    public void setHuntingMethod(final RequiredHarvestField huntingMethod) {
        this.huntingMethod = huntingMethod;
    }

    public RequiredHarvestField getReportedWithPhoneCall() {
        return reportedWithPhoneCall;
    }

    public void setReportedWithPhoneCall(final RequiredHarvestField reportedWithPhoneCall) {
        this.reportedWithPhoneCall = reportedWithPhoneCall;
    }

    public RequiredHarvestField getFeedingPlace() {
        return feedingPlace;
    }

    public void setFeedingPlace(final RequiredHarvestField feedingPlace) {
        this.feedingPlace = feedingPlace;
    }

    public RequiredHarvestField getTaigaBeanGoose() {
        return taigaBeanGoose;
    }

    public void setTaigaBeanGoose(final RequiredHarvestField taigaBeanGoose) {
        this.taigaBeanGoose = taigaBeanGoose;
    }

    public RequiredHarvestField getLukeStatus() {
        return lukeStatus;
    }

    public void setLukeStatus(final RequiredHarvestField lukeStatus) {
        this.lukeStatus = lukeStatus;
    }

    public RequiredHarvestField getDeerHuntingType() {
        return deerHuntingType;
    }

    public void setDeerHuntingType(final RequiredHarvestField deerHuntingType) {
        this.deerHuntingType = deerHuntingType;
    }
}
