# Development database for oma-riista-web
#
# Build:
# $ docker build -f Dockerfile.postgres -t oma-riista-db .
#
# Run:
# $ docker run -d -p 5432:5432 --name <dbname> oma-riista-db
#
# Initialization:
# $ ./init-development-db.sh localhost 5432
#

FROM postgres:12.3

# No password
ENV POSTGRES_HOST_AUTH_METHOD=trust

RUN apt-get update && apt-get install -y postgresql-12-postgis-2.5

EXPOSE 5432
