-- delete from rhy_annual_statistics_state_change_event;
-- delete from rhy_annual_statistics_moderator_update_event;
-- delete from rhy_annual_statistics;

WITH data AS (
  SELECT organisation_id,
         years.year,
         1000 * random()                               AS mooselike_damage_inspection_expenses,
         1000 * random()                               AS large_carnivore_damage_inspection_expenses,
         round(100 * random())                         AS hunter_exam_events,
         round(100 * random())                         AS passed_hunter_exams,
         round(100 * random())                         AS failed_hunter_exams,
         round(100 * random())                         AS hunter_exam_officials,
         round(100 * random())                         AS hunting_control_events,
         round(100 * random())                         AS hunting_control_customers,
         round(100 * random())                         AS proof_orders,
         round(100 * random())                         AS hunting_controllers,
         round(100 * random())                         AS game_damage_inspectors,
         round(100 * random())                         AS firearm_test_events,
         round(100 * random())                         AS bow_test_events,
         round(100 * random())                         AS all_moose_attempts,
         round(100 * random())                         AS qualified_moose_attempts,
         round(100 * random())                         AS all_bear_attempts,
         round(100 * random())                         AS qualified_bear_attempts,
         round(100 * random())                         AS all_roe_deer_attempts,
         round(100 * random())                         AS qualified_roe_deer_attempts,
         round(100 * random())                         AS all_bow_attempts,
         round(100 * random())                         AS qualified_bow_attempts,
         round(100 * random())                         AS shooting_test_officials,
         round(100 * random())                         AS granted_recreational_shooting_certificates,
         round(100 * random())                         AS mutual_ack_shooting_certificates,
         round(100 * random())                         AS jht_shooting_test_training_events,
         round(100 * random())                         AS jht_shooting_test_training_participants,
         round(100 * random())                         AS jht_hunter_exam_training_events,
         round(100 * random())                         AS jht_hunter_exam_training_participants,
         round(100 * random())                         AS jht_game_damage_training_events,
         round(100 * random())                         AS jht_game_damage_training_participants,
         round(100 * random())                         AS jht_hunting_control_training_events,
         round(100 * random())                         AS jht_hunting_control_training_participants,
         round(100 * random())                         AS mooselike_hunting_training_events,
         round(100 * random())                         AS mooselike_hunting_training_participants,
         round(100 * random())                         AS carnivore_hunting_training_events,
         round(100 * random())                         AS carnivore_hunting_training_participants,
         round(100 * random())                         AS carnivore_hunting_leader_training_events,
         round(100 * random())                         AS carnivore_hunting_leader_training_participants,
         round(100 * random())                         AS srva_training_events,
         round(100 * random())                         AS srva_training_participants,
         round(100 * random())                         AS carnivore_contact_person_training_events,
         round(100 * random())                         AS carnivore_contact_person_training_participants,
         round(100 * random())                         AS mooselike_hunting_leader_training_events,
         round(100 * random())                         AS mooselike_hunting_leader_training_participants,
         round(100 * random())                         AS small_carnivore_hunting_training_events,
         round(100 * random())                         AS small_carnivore_hunting_training_participants,
         round(100 * random())                         AS game_counting_training_events,
         round(100 * random())                         AS game_counting_training_participants,
         round(100 * random())                         AS game_population_management_training_events,
         round(100 * random())                         AS game_population_management_training_participants,
         round(100 * random())                         AS game_environmental_care_training_events,
         round(100 * random())                         AS game_environmental_care_training_participants,
         round(100 * random())                         AS other_gamekeeping_training_events,
         round(100 * random())                         AS other_gamekeeping_training_participants,
         round(100 * random())                         AS shooting_training_events,
         round(100 * random())                         AS shooting_training_participants,
         round(100 * random())                         AS tracker_training_events,
         round(100 * random())                         AS tracker_training_participants,
         round(100 * random())                         AS school_training_events,
         round(100 * random())                         AS school_training_participants,
         round(100 * random())                         AS college_training_events,
         round(100 * random())                         AS college_training_participants,
         round(100 * random())                         AS other_youth_targeted_training_events,
         round(100 * random())                         AS other_youth_targeted_training_participants,
         round(100 * random())                         AS public_events,
         round(100 * random())                         AS public_event_participants,
         round(100 * random())                         AS accident_prevention_training_events,
         round(100 * random())                         AS accident_prevention_training_participants,
         round(100 * random())                         AS hunter_exam_training_events,
         round(100 * random())                         AS hunter_exam_training_participants,
         round(100 * random())                         AS harvest_permit_application_partners,
         round(100 * random())                         AS interviews,
         round(100 * random())                         AS announcements,
         round(100 * random())                         AS omariista_announcements,
         round(100 * random())                         AS moose_ranges,
         round(100 * random())                         AS shotgun_ranges,
         round(100 * random())                         AS rifle_ranges,
         round(100 * random())                         AS other_shooting_ranges,
         round(100 * random())                         AS srva_moose_accidents,
         round(100 * random())                         AS srva_moose_deportations,
         round(100 * random())                         AS srva_moose_injuries,
         round(100 * random())                         AS srva_white_tailed_deer_accidents,
         round(100 * random())                         AS srva_white_tailed_deer_deportations,
         round(100 * random())                         AS srva_white_tailed_deer_injuries,
         round(100 * random())                         AS srva_roe_deer_accidents,
         round(100 * random())                         AS srva_roe_deer_deportations,
         round(100 * random())                         AS srva_roe_deer_injuries,
         round(100 * random())                         AS srva_wild_forest_reindeer_accidents,
         round(100 * random())                         AS srva_wild_forest_reindeer_deportations,
         round(100 * random())                         AS srva_wild_forest_reindeer_injuries,
         round(100 * random())                         AS srva_fallow_deer_accidents,
         round(100 * random())                         AS srva_fallow_deer_deportations,
         round(100 * random())                         AS srva_fallow_deer_injuries,
         round(100 * random())                         AS srva_wild_boar_accidents,
         round(100 * random())                         AS srva_wild_boar_deportations,
         round(100 * random())                         AS srva_wild_boar_injuries,
         round(100 * random())                         AS srva_lynx_accidents,
         round(100 * random())                         AS srva_lynx_deportations,
         round(100 * random())                         AS srva_lynx_injuries,
         round(100 * random())                         AS srva_bear_accidents,
         round(100 * random())                         AS srva_bear_deportations,
         round(100 * random())                         AS srva_bear_injuries,
         round(100 * random())                         AS srva_wolf_accidents,
         round(100 * random())                         AS srva_wolf_deportations,
         round(100 * random())                         AS srva_wolf_injuries,
         round(100 * random())                         AS srva_wolverine_accidents,
         round(100 * random())                         AS srva_wolverine_deportations,
         round(100 * random())                         AS srva_wolverine_injuries,
         round(100 * random())                         AS srva_total_work_hours,
         round(100 * random())                         AS srva_participants,
         round(100 * random())                         AS mooselike_damage_inspection_locations,
         round(100 * random())                         AS large_carnivore_damage_inspection_locations,
         round(100 * random())                         AS mh_small_game_sold_licenses,
         round(100 * random())                         AS wolf_territory_workgroups,
         round(10000 * random())                       AS rhy_members,
         round(100 * random())                         AS operational_land_area_size,
         round(100 * random())                         AS srva_traffic_accidents,
         round(100 * random())                         AS srva_railway_accidents,
         round(100 * random())                         AS srva_other_accidents,
         round(100 * random())                         AS luke_water_bird_broods,
         round(100 * random())                         AS mooselike_taxation_planning_events,
         round(100 * random())                         AS luke_carnivore_contact_persons,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS hunter_exams_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS hunting_control_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS game_damage_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS shooting_tests_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS other_admin_data_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS jht_trainings_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS hunter_trainings_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS other_hunter_trainings_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS public_events_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS hunter_exam_training_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS other_hunting_related_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS communication_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS shooting_ranges_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS luke_game_calculations_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS mh_last_modified,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS hunter_exam_events_last_overridden,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS firearm_test_events_last_overridden,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS bow_test_events_last_overridden,
         NOW() - RANDOM() * 1000 * (INTERVAL '1 hour') AS hunter_exam_training_events_last_overridden
  FROM organisation,
       (
         VALUES (EXTRACT('YEAR' FROM CURRENT_DATE)),
                (EXTRACT('YEAR' FROM CURRENT_DATE) - 1)
       ) years(year)
  WHERE organisation.organisation_type = 'RHY'
        -- Take real-world RHY merges into account.
        AND NOT (years.year = 2018 AND organisation.official_code = '078')
        AND NOT (years.year = 2019 AND organisation.official_code IN ('056', '060'))
)
INSERT
INTO rhy_annual_statistics (rhy_id, year, state, mooselike_damage_inspection_expenses,
                            large_carnivore_damage_inspection_expenses, hunter_exam_events, passed_hunter_exams,
                            failed_hunter_exams, hunter_exam_officials, hunting_control_events,
                            hunting_control_customers, proof_orders, hunting_controllers, game_damage_inspectors,
                            firearm_test_events, bow_test_events, all_moose_attempts, qualified_moose_attempts,
                            all_bear_attempts, qualified_bear_attempts, all_roe_deer_attempts,
                            qualified_roe_deer_attempts, all_bow_attempts, qualified_bow_attempts,
                            shooting_test_officials, granted_recreational_shooting_certificates,
                            mutual_ack_shooting_certificates, jht_shooting_test_training_events,
                            jht_shooting_test_training_participants, jht_hunter_exam_training_events,
                            jht_hunter_exam_training_participants, jht_game_damage_training_events,
                            jht_game_damage_training_participants, jht_hunting_control_training_events,
                            jht_hunting_control_training_participants, mooselike_hunting_training_events,
                            mooselike_hunting_training_participants, carnivore_hunting_training_events,
                            carnivore_hunting_training_participants, carnivore_hunting_leader_training_events,
                            carnivore_hunting_leader_training_participants, srva_training_events,
                            srva_training_participants, carnivore_contact_person_training_events,
                            carnivore_contact_person_training_participants, mooselike_hunting_leader_training_events,
                            mooselike_hunting_leader_training_participants, small_carnivore_hunting_training_events,
                            small_carnivore_hunting_training_participants, game_counting_training_events,
                            game_counting_training_participants, game_population_management_training_events,
                            game_population_management_training_participants, game_environmental_care_training_events,
                            game_environmental_care_training_participants, other_gamekeeping_training_events,
                            other_gamekeeping_training_participants, shooting_training_events,
                            shooting_training_participants, tracker_training_events,
                            tracker_training_participants, school_training_events, school_training_participants,
                            college_training_events, college_training_participants,
                            other_youth_targeted_training_events, other_youth_targeted_training_participants,
                            public_events, public_event_participants, accident_prevention_training_events,
                            accident_prevention_training_participants, hunter_exam_training_events,
                            hunter_exam_training_participants, harvest_permit_application_partners, interviews,
                            announcements, omariista_announcements, moose_ranges, shotgun_ranges, rifle_ranges,
                            other_shooting_ranges, srva_moose_accidents, srva_moose_deportations, srva_moose_injuries,
                            srva_white_tailed_deer_accidents, srva_white_tailed_deer_deportations,
                            srva_white_tailed_deer_injuries, srva_roe_deer_accidents, srva_roe_deer_deportations,
                            srva_roe_deer_injuries, srva_wild_forest_reindeer_accidents,
                            srva_wild_forest_reindeer_deportations, srva_wild_forest_reindeer_injuries,
                            srva_fallow_deer_accidents, srva_fallow_deer_deportations, srva_fallow_deer_injuries,
                            srva_wild_boar_accidents, srva_wild_boar_deportations, srva_wild_boar_injuries,
                            srva_lynx_accidents, srva_lynx_deportations, srva_lynx_injuries, srva_bear_accidents,
                            srva_bear_deportations, srva_bear_injuries, srva_wolf_accidents, srva_wolf_deportations,
                            srva_wolf_injuries, srva_wolverine_accidents, srva_wolverine_deportations,
                            srva_wolverine_injuries, srva_total_work_hours, srva_participants,
                            mooselike_damage_inspection_locations, large_carnivore_damage_inspection_locations,
                            mh_small_game_sold_licenses, wolf_territory_workgroups, rhy_members,
                            operational_land_area_size, srva_traffic_accidents, srva_railway_accidents,
                            srva_other_accidents, luke_water_bird_broods, mooselike_taxation_planning_events,
                            luke_carnivore_contact_persons, hunter_exams_last_modified, hunting_control_last_modified,
                            game_damage_last_modified, shooting_tests_last_modified, other_admin_data_last_modified,
                            jht_trainings_last_modified, hunter_trainings_last_modified,
                            other_hunter_trainings_last_modified, public_events_last_modified,
                            hunter_exam_training_last_modified, other_hunting_related_last_modified,
                            communication_last_modified, shooting_ranges_last_modified,
                            luke_game_calculations_last_modified, mh_last_modified, hunter_exam_events_last_overridden,
                            firearm_test_events_last_overridden, bow_test_events_last_overridden,
                            hunter_exam_training_events_last_overridden)
SELECT organisation_id,
       data.year,
       'IN_PROGRESS',
       mooselike_damage_inspection_expenses,
       large_carnivore_damage_inspection_expenses,
       hunter_exam_events,
       passed_hunter_exams,
       failed_hunter_exams,
       hunter_exam_officials,
       hunting_control_events,
       hunting_control_customers,
       proof_orders,
       hunting_controllers,
       game_damage_inspectors,
       firearm_test_events,
       bow_test_events,
       all_moose_attempts,
       qualified_moose_attempts,
       all_bear_attempts,
       qualified_bear_attempts,
       all_roe_deer_attempts,
       qualified_roe_deer_attempts,
       all_bow_attempts,
       qualified_bow_attempts,
       shooting_test_officials,
       granted_recreational_shooting_certificates,
       mutual_ack_shooting_certificates,
       jht_shooting_test_training_events,
       jht_shooting_test_training_participants,
       jht_hunter_exam_training_events,
       jht_hunter_exam_training_participants,
       jht_game_damage_training_events,
       jht_game_damage_training_participants,
       jht_hunting_control_training_events,
       jht_hunting_control_training_participants,
       mooselike_hunting_training_events,
       mooselike_hunting_training_participants,
       carnivore_hunting_training_events,
       carnivore_hunting_training_participants,
       carnivore_hunting_leader_training_events,
       carnivore_hunting_leader_training_participants,
       srva_training_events,
       srva_training_participants,
       carnivore_contact_person_training_events,
       carnivore_contact_person_training_participants,
       mooselike_hunting_leader_training_events,
       mooselike_hunting_leader_training_participants,
       small_carnivore_hunting_training_events,
       small_carnivore_hunting_training_participants,
       game_counting_training_events,
       game_counting_training_participants,
       game_population_management_training_events,
       game_population_management_training_participants,
       game_environmental_care_training_events,
       game_environmental_care_training_participants,
       other_gamekeeping_training_events,
       other_gamekeeping_training_participants,
       shooting_training_events,
       shooting_training_participants,
       tracker_training_events,
       tracker_training_participants,
       school_training_events,
       school_training_participants,
       college_training_events,
       college_training_participants,
       other_youth_targeted_training_events,
       other_youth_targeted_training_participants,
       public_events,
       public_event_participants,
       accident_prevention_training_events,
       accident_prevention_training_participants,
       hunter_exam_training_events,
       hunter_exam_training_participants,
       harvest_permit_application_partners,
       interviews,
       announcements,
       omariista_announcements,
       moose_ranges,
       shotgun_ranges,
       rifle_ranges,
       other_shooting_ranges,
       srva_moose_accidents,
       srva_moose_deportations,
       srva_moose_injuries,
       srva_white_tailed_deer_accidents,
       srva_white_tailed_deer_deportations,
       srva_white_tailed_deer_injuries,
       srva_roe_deer_accidents,
       srva_roe_deer_deportations,
       srva_roe_deer_injuries,
       srva_wild_forest_reindeer_accidents,
       srva_wild_forest_reindeer_deportations,
       srva_wild_forest_reindeer_injuries,
       srva_fallow_deer_accidents,
       srva_fallow_deer_deportations,
       srva_fallow_deer_injuries,
       srva_wild_boar_accidents,
       srva_wild_boar_deportations,
       srva_wild_boar_injuries,
       srva_lynx_accidents,
       srva_lynx_deportations,
       srva_lynx_injuries,
       srva_bear_accidents,
       srva_bear_deportations,
       srva_bear_injuries,
       srva_wolf_accidents,
       srva_wolf_deportations,
       srva_wolf_injuries,
       srva_wolverine_accidents,
       srva_wolverine_deportations,
       srva_wolverine_injuries,
       srva_total_work_hours,
       srva_participants,
       mooselike_damage_inspection_locations,
       large_carnivore_damage_inspection_locations,
       mh_small_game_sold_licenses,
       wolf_territory_workgroups,
       rhy_members,
       operational_land_area_size,
       srva_traffic_accidents,
       srva_railway_accidents,
       srva_other_accidents,
       luke_water_bird_broods,
       mooselike_taxation_planning_events,
       luke_carnivore_contact_persons,
       hunter_exams_last_modified,
       hunting_control_last_modified,
       game_damage_last_modified,
       shooting_tests_last_modified,
       other_admin_data_last_modified,
       jht_trainings_last_modified,
       hunter_trainings_last_modified,
       other_hunter_trainings_last_modified,
       public_events_last_modified,
       hunter_exam_training_last_modified,
       other_hunting_related_last_modified,
       communication_last_modified,
       shooting_ranges_last_modified,
       luke_game_calculations_last_modified,
       mh_last_modified,
       hunter_exam_events_last_overridden,
       firearm_test_events_last_overridden,
       bow_test_events_last_overridden,
       hunter_exam_training_events_last_overridden
FROM data;
