package fi.riista.feature.organization.rhy.annualstats;

public enum AnnualStatisticsParticipantFieldGroup {
    YOUTH_TRAINING_STATISTICS,
    HUNTER_EXAM_STATISTICS,
    HUNTER_EXAM_TRAINING_STATISTICS,
    HUNTER_TRAINING_STATISTICS,
    HUNTING_CONTROL_STATISTICS,
    JHT_TRAINING_STATISTICS,
    OTHER_HUNTER_TRAINING_STATISTICS,
    PUBLIC_EVENT_STATISTICS
}
